import { chromium } from 'playwright';
const b = await chromium.launch({ channel: 'chrome', args: ['--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto('https://hedongli1.github.io/ai-model-world/', { waitUntil: 'domcontentloaded', timeout: 90000 });
await p.waitForTimeout(6000);
await p.screenshot({ path: '/tmp/top.png' });
await p.evaluate(() => window.scrollTo(0, 1200));
await p.waitForTimeout(2000);
await p.screenshot({ path: '/tmp/mid.png' });
console.log('ok');
await b.close();
