import { chromium } from 'playwright';
const b = await chromium.launch({ channel: 'chrome', args: ['--no-sandbox'] });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
await p.goto('http://127.0.0.1:8899/', { waitUntil: 'domcontentloaded', timeout: 60000 });
await p.waitForTimeout(5000);
await p.screenshot({ path: '/tmp/v2-top.png' });
await p.evaluate(() => window.scrollTo(0, 1100));
await p.waitForTimeout(2000);
await p.screenshot({ path: '/tmp/v2-mid.png' });
console.log('ok-v2');
await b.close();
